import chalk from "chalk";
import { existsSync, readFileSync } from "fs";
import { resolve } from "path";
import { loadConfig } from "../config.js";
import { writeFileSafe } from "../utils.js";

interface GenerateClaudeOptions {
  force?: boolean;
  projectName?: string;
  output?: string;
}

export async function generateClaudeCommand(
  projectRoot: string,
  options: GenerateClaudeOptions
): Promise<void> {
  const config = loadConfig(projectRoot);
  const outputFile = options.output
    ? resolve(projectRoot, options.output)
    : resolve(projectRoot, config.context.project_file);

  if (existsSync(outputFile) && !options.force) {
    console.log(chalk.yellow(`⚠️  ${outputFile} already exists. Use --force to overwrite.`));
    return;
  }

  const projectName = options.projectName ?? detectProjectName(projectRoot);
  const content = buildClaudeMd(projectName, projectRoot, config);

  writeFileSafe(outputFile, content);
  console.log(chalk.green(`\n✅ Generated ${outputFile}\n`));
  console.log(chalk.gray("   Review and edit it to match your project.\n"));
}

function detectProjectName(projectRoot: string): string {
  const pkgPath = resolve(projectRoot, "package.json");
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as { name?: string };
      if (pkg.name) return pkg.name;
    } catch {
      // ignore
    }
  }
  return projectRoot.split("/").pop() ?? "my-project";
}

function buildClaudeMd(
  projectName: string,
  projectRoot: string,
  config: ReturnType<typeof loadConfig>
): string {
  const backend = config.backend;
  const model = config.model ?? "(default)";
  const guardMode = config.guardrails.mode;
  const allowedTools = config.guardrails.allowed_tools.join(", ");
  const confirmDestructive = config.guardrails.confirm_destructive ? "yes" : "no";
  const maxContext = config.token_budget.max_context.toLocaleString();
  const reserveForOutput = config.token_budget.reserve_for_output.toLocaleString();
  const featureList = config.context.feature_list;
  const handoff = config.context.handoff;
  const traceDir = config.observability.trace_dir;
  const hasQualityGates = config.quality_gates && config.quality_gates.length > 0;

  const gatesSection = hasQualityGates
    ? `\n## Quality Gates\n\nBefore finishing any task, run these checks:\n\n${
        config.quality_gates!
          .map((g) => `- \`${g.command}\` — ${g.name}`)
          .join("\n")
      }\n`
    : "";

  return `# ${projectName}

<!-- Generated by HarnessFlow: harness generate-claude -->
<!-- Edit this file to give the AI agent full project context. -->

## What this project does

[Describe your project here — what problem it solves, what it does, who uses it.]

## Tech stack

[List your main technologies, e.g.:]
- Language: TypeScript / Node.js
- Framework: Express / React / Next.js
- Database: PostgreSQL / SQLite
- Testing: Jest / Vitest

## Repository layout

[Describe the key directories, e.g.:]
- \`src/\` — main source code
- \`tests/\` — test files
- \`docs/\` — documentation

## How to work on this project

\`\`\`bash
# Install dependencies
pnpm install

# Start development server
pnpm dev

# Run tests
pnpm test

# Type-check
pnpm typecheck

# Build
pnpm build
\`\`\`

## Important conventions

- Write tests for every new feature
- Keep functions small and focused
- Use descriptive variable names
- Commit early and often with clear messages
- Do not delete code without asking first
- Ask before major refactors

## HarnessFlow settings (auto-generated)

This project uses **HarnessFlow** to manage AI coding sessions.

| Setting | Value |
|---------|-------|
| Backend | ${backend} |
| Model | ${model} |
| Guardrail mode | ${guardMode} |
| Allowed tools | ${allowedTools} |
| Confirm destructive actions | ${confirmDestructive} |
| Max context tokens | ${maxContext} |
| Reserved for output | ${reserveForOutput} |
| Feature list | \`${featureList}\` |
| Handoff artifact | \`${handoff}\` |
| Trace logs | \`${traceDir}/\` |
${gatesSection}
## Session rules for AI agent

1. **Read first**: Before coding, read the handoff artifact at \`${handoff}\`
2. **Check features**: Read \`${featureList}\` to see what's done and what's next
3. **Work incrementally**: Make small changes, verify with tests or typechecks
4. **Update the feature list**: Mark items as WIP while working, DONE when complete
5. **Write the handoff**: At the end of your session, update \`${handoff}\` with:
   - What you accomplished
   - What still needs to be done
   - Any blockers you encountered
   - Which files are most important
6. **Don't rush**: If you're unsure about something, stop and ask

## What "done" looks like

- All acceptance criteria in the task are met
- Tests pass (\`pnpm test\`)
- Types check (\`pnpm typecheck\`)
- Code is committed
- Handoff artifact is up to date
`;
}
